---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: json/calendar.json
  label: Calendar
  match: "**/*"
- type: directory
  path: posts
  label: Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: document
  path: json/carousel.json
  label: Carousel
upload_dir: public/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - CONTEXT=dev
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
