---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "**/*"
  new_doc_ext: '20200129184523'
upload_dir: static/pictures
public_path: "/pictures"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GATSBY_GRAPHQL_IDE=playground
  - CONTEXT=dev
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
